### ISSUE TITLE
Initital project configuration

### ISSUE THREAD

**Issue by Ruberoni** [chingu-voyages/v34-bears-team-06#20]
**__Feature Description__**
Steps to start the initial project configuration and the initial codebase.

**__Major User Stories/tasks__**
- [x] Create branches
- [x] Initialize frontend framework Next.js
- [x] Setup linters and code formatters
- [x] Install main modules: Express, mongoose...
- [x] Create MongoDB database
- [x] Connect MongoDB database with the app
- [ ] Deploy
