### ISSUE TITLE
Version 1

### ISSUE THREAD

**Issue by Ruberoni** [chingu-voyages/v34-bears-team-06#32]
## Overview
This is a summary of the steps to follow to get the MVP ready at the Voyage end line (around November 11), nicknamed as Version 1.

### Expected state
Any user will be able to:
- See a list of residents
- Click on any item of the list and go to the dashboard of each resident
- Create a resident attached to a Menu, the only menu in the DB
- Edit a resident's info
- See and update a resident's eating history

## Current state
(as for November 6)
- Display resident's info | Ready ✅
- Create a resident | Ready ✅
- Edit a resident | Ready ✅
- Resident's calories stats | Ready ✅
- Resident's eating history edit | Dev🛠
- Resident's menu week | Dev🛠 

## Task list
- [x] Make resident's eating history edit call the API to update the DB
  - [x] API controller to handle edit an eating history entry
- [x] Get more consistent loading of the EatingHistoryModal's data. Make clickable and to update through the modal.
- [x] #34
- [x] Fix resident's menu week to get the correct menu day based on current day
- [x] Improve dashboard page to be able to get any resident's data through the URL
- [x] Resident's data insights
- [x] #33 
- [x] #35

**Possible tasks that won't be ready to end line:**
- [ ] CRUD Meal
- [ ] CRUD Menu
- [ ] Link and unlink resident to menu
- [ ] Home page
