### ISSUE TITLE
Meals list popover

### ISSUE THREAD

**Issue by Ruberoni** [chingu-voyages/v34-bears-team-06#40]
## Tasks
- [x] Create meals list popover
- [x] Integrate it in EatingHistoryForm

## List
- [x] Show meals in the menu
  - [x] Function to get unique meals in the menu. 
- [ ] Show meals sorted by day number of menu, then sorted by meal time. As menu days are sorted in ascending order, only need to iterate the menu days to get those sorted by day number
  - [ ]  Function to sort meals by meal_time
- [ ] Loading indicator 

### Information to display
- Role
- Title
- Proteins
- Carbs
- Fat

### Functionality
- Buttons 
- Responsive
- Easy to know if its a meal or a snack

## Extras
- Focus to meal selected
- Filter by `meal_role`
- Filter by `meal_type` (Meal or Snack)
- User can decide to show the exact menu order (i.e. with duplicates)
- Display the day of menu that the meal belongs to
- Search meals
- Way to know if there are more items 
- Ability to change between meals in the menu and all the meals

## User flow
1. User click on **Register a Meal** button
2. Modal appears with meal input prepopulated with possible next meal
3. Meal list appears with focus on value of the meal input
4. User click in a meal
5. Meal input gets the data of the meal selected
6. User click submit
7. Data is send to the server

### Cannot trust in the order of the Menu days
If I could trust in the order of the Menu days, I just need to iterate the Menu days, then get the meals and snacks of each. That way I have the meals and snack sorted by menu day.

The problem is that, different days in a Menu can have same meals, so I will have repeated meals in the list. That's very bad. So sorting by menu day isn't an option.\
That's why search, filtering and having the meal input prepopulated with possible next meal are so important.

### So, whats the order
The order of the Menu days, but everytime there's a duplicated, it will be removed.
Example.
```javascript
// not important information is omitted
// Menu
{
  ...menuData,
  days: [
    {
      day_number: 1,
      meals: [meal334, meal217]
    },
    {
      day_number: 2,
      meals: [meal334, meal421]
    },
  ]
}
// Unique meals from menu, this will be the order of the meals list
[
  meal334,
  meal217,
  meal421,
]
```
Will look like random by it won't be.
